apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: CICDTEST
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu 
      targetAverageUtilization: 10
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-spring-deployment
